# Generated by Django 4.1 on 2022-08-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='Write A Comment...', max_length=400),
        ),
    ]
